//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maseya.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maseya.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -rand-pal.
        /// </summary>
        internal static string DefaultOutputNameSuffix {
            get {
                return ResourceManager.GetString("DefaultOutputNameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of collection exceeds capacity of target..
        /// </summary>
        internal static string ErrorCollectionBounds {
            get {
                return ResourceManager.GetString("ErrorCollectionBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection may only have unique values..
        /// </summary>
        internal static string ErrorCollectionMustBeUniqueValues {
            get {
                return ResourceManager.GetString("ErrorCollectionMustBeUniqueValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have an empty collection..
        /// </summary>
        internal static string ErrorEmptyCollection {
            get {
                return ResourceManager.GetString("ErrorEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum and maximum index fall outside bounds of array..
        /// </summary>
        internal static string ErrorIndexBounds {
            get {
                return ResourceManager.GetString("ErrorIndexBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null value exists in the collection where none were expected..
        /// </summary>
        internal static string ErrorNullInCollection {
            get {
                return ResourceManager.GetString("ErrorNullInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object of type {0} was passed to a object expecting a type of {1}..
        /// </summary>
        internal static string ErrorObjectType {
            get {
                return ResourceManager.GetString("ErrorObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start index and size exceed size of collection..
        /// </summary>
        internal static string ErrorOffsetBounds {
            get {
                return ResourceManager.GetString("ErrorOffsetBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} is infinite. A finite value was expected..
        /// </summary>
        internal static string ErrorValueIsInfinity {
            get {
                return ResourceManager.GetString("ErrorValueIsInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} is NaN. A real number was expected..
        /// </summary>
        internal static string ErrorValueIsNaN {
            get {
                return ResourceManager.GetString("ErrorValueIsNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &apos;{1}&apos; is not valid for &apos;{0}&apos;. &apos;{0}&apos; must be greater than {2}..
        /// </summary>
        internal static string ErrorValueNotGreaterThan {
            get {
                return ResourceManager.GetString("ErrorValueNotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &apos;{1}&apos; is not valid for &apos;{0}&apos;. &apos;{0}&apos; must be greater than or equal to {2}..
        /// </summary>
        internal static string ErrorValueNotGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("ErrorValueNotGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &apos;{1}&apos; is not valid for &apos;{0}&apos;. &apos;{0}&apos; cannot be negative and must be and less than &apos;{2}&apos;..
        /// </summary>
        internal static string ErrorValueNotInArrayBounds {
            get {
                return ResourceManager.GetString("ErrorValueNotInArrayBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &apos;{1}&apos; is not valid for &apos;{0}&apos;. &apos;{0}&apos; must be less than {2}..
        /// </summary>
        internal static string ErrorValueNotLessThan {
            get {
                return ResourceManager.GetString("ErrorValueNotLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &apos;{1}&apos; is not valid for &apos;{0}&apos;. &apos;{0}&apos; must be less than or equal to {2}..
        /// </summary>
        internal static string ErrorValueNotLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("ErrorValueNotLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --no-use-json
        ///--overworld
        ///--dungeon
        ///--no-link-sprite
        ///--no-sword
        ///--no-shield
        ///--mode=default
        ///--no-sprite
        ///--no-sprite2
        ///--no-hud
        ///--seed=-1.
        /// </summary>
        internal static string FallbackConfig {
            get {
                return ResourceManager.GetString("FallbackConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit codes:
        /// 0: Program terminated successfully.
        /// 1: No input given.
        ///-1: I/O error occurred.
        ///.
        /// </summary>
        internal static string InfoExitCodes {
            get {
                return ResourceManager.GetString("InfoExitCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input path to base ROM:.
        /// </summary>
        internal static string PromptForInputPath {
            get {
                return ResourceManager.GetString("PromptForInputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input output path to save ROM (leave empty for same as input):.
        /// </summary>
        internal static string PromptForOutputPath {
            get {
                return ResourceManager.GetString("PromptForOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize dungeon palettes? [Y]/n.
        /// </summary>
        internal static string PromptRandomizeDungeon {
            get {
                return ResourceManager.GetString("PromptRandomizeDungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize hud palettes? Y/[n].
        /// </summary>
        internal static string PromptRandomizeHud {
            get {
                return ResourceManager.GetString("PromptRandomizeHud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Link sprite palette? Y/[n].
        /// </summary>
        internal static string PromptRandomizeLinkSprite {
            get {
                return ResourceManager.GetString("PromptRandomizeLinkSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize overworld palettes? [Y]/n.
        /// </summary>
        internal static string PromptRandomizeOverworld {
            get {
                return ResourceManager.GetString("PromptRandomizeOverworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter randomizer mode (none, [default], blackout, negative, grayscale, puke).
        /// </summary>
        internal static string PromptRandomizerMode {
            get {
                return ResourceManager.GetString("PromptRandomizerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize shield palettes? Y/[n].
        /// </summary>
        internal static string PromptRandomizeShield {
            get {
                return ResourceManager.GetString("PromptRandomizeShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize sword palettes? Y/[n].
        /// </summary>
        internal static string PromptRandomizeSword {
            get {
                return ResourceManager.GetString("PromptRandomizeSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom seed (leave blank for default):.
        /// </summary>
        internal static string PromptSeed {
            get {
                return ResourceManager.GetString("PromptSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse input.
        /// </summary>
        internal static string StatusInvalidInput {
            get {
                return ResourceManager.GetString("StatusInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input was given. Terminating program..
        /// </summary>
        internal static string StatusNoInputGiven {
            get {
                return ResourceManager.GetString("StatusNoInputGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task completed successfully!
        ///Press any key to exit....
        /// </summary>
        internal static string StatusSuccessfulTermination {
            get {
                return ResourceManager.GetString("StatusSuccessfulTermination", resourceCulture);
            }
        }
    }
}
